print("welkom in het avontuur")
print("het wijst zichzelf wel uit")
print("daar is het eerste monster")
print("ik ben een rat level 2")
hprat = "2"
print("welke aanval wil je doen")
print("kak gooien (+3)")
print("zeiken op dat ding jonge(-3)")
aanval = raw_input("wat kies je? ")
print(aanval + " mooie keuze")
